# Generated by Django 2.1.3 on 2018-12-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_match2_rating2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Event (2 Field)', 'verbose_name_plural': 'Event (2 Fields)'},
        ),
        migrations.AlterModelOptions(
            name='match2',
            options={'verbose_name': 'Event (1 Field)', 'verbose_name_plural': 'Event (1 Fields)'},
        ),
    ]
